name: Mirror to gitee Repo

on: [push, delete, create]

concurrency:
    group: git-mirror

jobs:
    git-mirror:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
              with:
                  source-repo: "git@github.com:sakurastone/egg-example.git"
                  destination-repo: "git@gitee.com:sakurastone/egg-example.git"
